# Generated by Django 5.0.7 on 2024-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
